# Generated by Django 4.2.7 on 2023-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_comments_project_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('organisation', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('areas_of_interest', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
