# Generated by Django 4.2.7 on 2023-11-28 13:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profiles_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='areas_of_interest',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='picture',
            field=models.ImageField(default='post/default.png', upload_to=api.models.upload_to, verbose_name='image'),
        ),
    ]
