# Generated by Django 4.2.7 on 2023-11-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profiles_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
    ]
